name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Cambia a "master" si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: 'deployment'.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Aquí le indicamos a GitHub que tu web está dentro de src
          path: './scr'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
